import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#131313',
        'outline-variant': '#3b494b',
        'surface-bright': '#3a3939',
        'on-secondary-fixed': '#002022',
        'primary-container': '#00f0ff',
        secondary: '#96d1d6',
        primary: '#dbfcff',
        'on-surface': '#e5e2e1',
        'on-error-container': '#ffdad6',
        'inverse-on-surface': '#313030',
        'surface-container-lowest': '#0e0e0e',
        'error-container': '#93000a',
        'on-background': '#e5e2e1',
        'on-tertiary': '#3b2f00',
        'on-tertiary-container': '#715d00',
        error: '#ffb4ab',
        'surface-container': '#201f1f',
        surface: '#131313',
        'on-secondary-container': '#84bfc5',
        'primary-fixed-dim': '#00dbe9',
        'inverse-primary': '#006970',
        'on-tertiary-fixed-variant': '#554500',
        'on-primary': '#00363a',
        'inverse-surface': '#e5e2e1',
        tertiary: '#fff5de',
        'on-primary-fixed-variant': '#004f54',
        'secondary-fixed': '#b1edf3',
        'surface-container-low': '#1c1b1b',
        'on-tertiary-fixed': '#231b00',
        'on-primary-container': '#006970',
        'on-secondary-fixed-variant': '#074f54',
        'surface-variant': '#353534',
        'surface-dim': '#131313',
        'tertiary-fixed': '#ffe179',
        'surface-tint': '#00dbe9',
        'on-error': '#690005',
        'secondary-container': '#074f54',
        'on-secondary': '#00363a',
        'tertiary-fixed-dim': '#eac324',
        'on-surface-variant': '#b9cacb',
        'on-primary-fixed': '#002022',
        'tertiary-container': '#fed639',
        'surface-container-high': '#2a2a2a',
        outline: '#849495',
        'surface-container-highest': '#353534',
        'primary-fixed': '#7df4ff',
        'secondary-fixed-dim': '#96d1d6',
      },
      borderRadius: {
        sm: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['var(--font-manrope)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        label: ['var(--font-inter)', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}

export default config
